/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.generator;

import fr.ut2j.m1ice.fsm.FSM;
import fr.ut2j.m1ice.fsm.Final;
import fr.ut2j.m1ice.fsm.Initial;
import fr.ut2j.m1ice.fsm.State;
import fr.ut2j.m1ice.fsm.Transition;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.Conversions;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IterableExtensions;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class MyDslGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    EObject _get = resource.getContents().get(0);
    FSM fsm = ((FSM) _get);
    fsa.generateFile("FSM.java", this.generateFSM(fsm));
    fsa.generateFile("STATE.java", this.generateSTATE());
    fsa.generateFile("ABSTRACTSTATE.java", this.generateAbstractSTATE());
    fsa.generateFile("TRANSITION.java", this.generateTRANSITION());
  }
  
  public String generateTRANSITION() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append(" ");
    _builder.append("public class TRANSITION {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("private ABSTRACTSTATE STATEStart;");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("private ABSTRACTSTATE STATEEnd;");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("private String trigger;");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("public TRANSITION(ABSTRACTSTATE src, ABSTRACTSTATE target, String trigger) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("this.STATEStart = src;");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("this.STATEEnd = target;");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("this.trigger = trigger;");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("public ABSTRACTSTATE getSTATEStart() { return this.STATEStart; }");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("public ABSTRACTSTATE getSTATEEnd() { return this.STATEEnd; }");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("public String getTrigger() { return this.trigger; }");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("} ");
    return _builder.toString();
  }
  
  public String generateFSM(final FSM fsm) {
    final Function1<State, Boolean> _function = (State STATE) -> {
      return Boolean.valueOf((STATE instanceof Initial));
    };
    State initSTATE = ((State[])Conversions.unwrapArray(IterableExtensions.<State>filter(fsm.getState(), _function), State.class))[0];
    final Function1<State, Boolean> _function_1 = (State STATE) -> {
      return Boolean.valueOf((STATE instanceof Final));
    };
    State finalSTATE = ((State[])Conversions.unwrapArray(IterableExtensions.<State>filter(fsm.getState(), _function_1), State.class))[0];
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("import java.util.Scanner;");
    _builder.newLine();
    _builder.append("import java.util.List;");
    _builder.newLine();
    _builder.append("import java.util.ArrayList;");
    _builder.newLine();
    _builder.append("public class FSM {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void execute() {\t\t\t\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("List<TRANSITION> TRANSITIONs = new ArrayList<>();");
    _builder.newLine();
    {
      EList<Transition> _transition = fsm.getTransition();
      for(final Transition tr : _transition) {
        _builder.append("\t\t");
        _builder.append("TRANSITIONs.add(new TRANSITION(new STATE(\"");
        String _name = tr.getState1().getName();
        _builder.append(_name, "\t\t");
        _builder.append("\"), new STATE(\"");
        String _name_1 = tr.getState2().getName();
        _builder.append(_name_1, "\t\t");
        _builder.append("\"), \"");
        String _name_2 = tr.getName();
        _builder.append(_name_2, "\t\t");
        _builder.append("\"));");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("\t\t");
    _builder.append("Scanner sc = new Scanner(System.in);\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("ABSTRACTSTATE current = new STATE(\"");
    String _name_3 = initSTATE.getName();
    _builder.append(_name_3, "\t\t");
    _builder.append("\");");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("ABSTRACTSTATE finalSTATE = new STATE(\"");
    String _name_4 = finalSTATE.getName();
    _builder.append(_name_4, "\t\t");
    _builder.append("\");");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("while(!current.equals(finalSTATE)) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("System.out.println(\"COURANT : \" + current.getSTATE());");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("final ABSTRACTSTATE currentSTATE = current;");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("System.out.println(\"TRANSITION : \");");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("String trigger = sc.nextLine(); ");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("TRANSITION TRANSITION = TRANSITIONs.stream()");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append(".filter(tr -> tr.getSTATEStart().equals(currentSTATE) && tr.getTrigger().equals(trigger)).findFirst().orElse(null);");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("if (TRANSITION != null) {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("current = TRANSITION.getSTATEEnd();");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("} else {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("System.out.println(\"STATE : \" + current.getSTATE());");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("System.out.println(\"FIN\");");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public static void main(String[] args) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("FSM fsm = new FSM();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("fsm.execute();");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    return _builder.toString();
  }
  
  public String generateAbstractSTATE() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("import java.util.Objects;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("public abstract class ABSTRACTSTATE {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("private String STATE;");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("public ABSTRACTSTATE(String st){");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("this.STATE = st;}");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("public String getSTATE() {return this.STATE;}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("public void setSTATE( String newSt) {this.STATE = newSt;}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("public boolean equals(Object o) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("if (this == o) return true;");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("if (o == null || getClass() != o.getClass()) return false;");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("ABSTRACTSTATE that = (ABSTRACTSTATE) o;");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("return Objects.equals(STATE, that.STATE);");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.newLine();
    _builder.append("}");
    return _builder.toString();
  }
  
  public String generateSTATE() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("public class STATE extends ABSTRACTSTATE {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("public STATE(String name) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("super(name);");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("}");
    return _builder.toString();
  }
}
